# Generated by Django 5.1.1 on 2024-10-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_node_api_node_id_9e7a27_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
