# Generated by Django 5.1.1 on 2024-10-02 12:19

import api.models.node
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mindmap_id_alter_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(default=api.models.node.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
