# Generated by Django 5.1.1 on 2024-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_mindmap_id_alter_node_id_alter_node_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='id',
            field=models.CharField(default='3e68ad09b0e446d98a4d', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(default='95fc0c3bd0df4d76ac13cf98da1a6521', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
