# Generated by Django 5.1.1 on 2024-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_mindmap_id_alter_node_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mindmap",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
